make cudnn_conv CUCL stub template use DYN for all ins/outs
but leave REF's as non-DYN, since that still isn't quite there
yet. seems like we're close, though! if the REFs are made DYN, and a
test case is run like this one (or the existing test should fail similarly too):

boda cnn_op_info --rtc='(be=nvrtc,gen_src=1)' --compile-opts='(show_rtc_calls=1)' --gen-data='(str_vals=(type=gen_data),nda_vals=(vi=(tn=float,v=0.0),mode=(tn=uint32_t,v=5)))'  --cnn-func-sigs-fn='%(boda_test_dir)/conv-ops-debug.txt' --op-tune='(use_culibs=1)'

the error is the usual:
error: cudnnSetConvolution2dDescriptor() failed with ret=3 (CUDNN_STATUS_BAD_PARAM)

but now, the needed data is present inside cucl_arg_info; just not in
a form that the cuDNN glue code can easily deal with. and 'full'
arg-map is only availible at the rtc_codegen_t level, which is
dutifully extracting the relevant DYN info for the REFS and putting it
into the cucl_arg_info ...