ocl_util: add pre-emptive error check related to work group size limits
in cases that would have failed with this message before:

error: clEnqueueNDRangeKernel()() failed with ret=-54 (CL_INVALID_WORK_GROUP_SIZE)

you should now get this instead:

error: Error: can't run kernel: loc_work_sz is 120 but OpenCL says max is 64 for this kernel+device.

which is a bit more informative. other cases might still yield the
above error, although none are currently known.